### ISSUE TITLE
Add labels to specify which sub-project the issue goes to

### ISSUE THREAD

**Issue by asclines** [JohnCalhoun/Flamingo#15]
To enhance communication add labels such as:
- communication
- loadbalancer
- etc..

If not, what alternative might accomplish this purpose?

**Comment by asclines** [comment]
Also, I cannot add labels to issues, without contributor rights.

**Comment by JohnCalhoun** [comment]
I have added your as a contributor.
what all labels would be good?

**Comment by asclines** [comment]
As specified in #12 specification files and outlines need to be created for each 'project'.
Since each project will be self-contained, in order to manage issues, I propose that each 'project' gets its own label. Am I correct to assume that each folder in the main directory of this repository are 'project's?

**Comment by JohnCalhoun** [comment]
yes each project will have its own
yes each folder is its own project

**Comment by JohnCalhoun** [comment]
scheduler, communicator,allocator,load balancer, and agent def tags create
as well as corresponding milestones
