### ISSUE TITLE
Static implementation of Transporter class

### ISSUE THREAD

**Issue by asclines** [JohnCalhoun/Flamingo#25]
The Transporter class should be of a static state. 
That being said, should the Transporter class be a class consisting of static methods, or should the class follow a singleton design pattern?

After some thought, I believe that the decision weighs on which of these two situations more accurately describes how the Transporter class will work.
- The methods will need data members in this class or 
- The methods will be able to get all the data they need through passed in parameters.

**Comment by JohnCalhoun** [comment]
I think the transporter can do all its work through pass in parameters. 

I added a static std::map inside the dataframe class that will keep track of all the dataframes on a computer. This location seems more natural then in the transporter class
