### ISSUE TITLE
MPI Library

### ISSUE THREAD

**Issue by asclines** [JohnCalhoun/Flamingo#28]
Should project use standard MPI or Boost MPI?

Thoughts:
Seeing as this project is built in CPP and already uses Boost elsewhere in the project, it would make since to keep this consistency and use Boost MPI which brings in a CPP friendly MPI interface

For more reading:
http://www.boost.org/doc/libs/1_60_0/doc/html/mpi.html

**Comment by JohnCalhoun** [comment]
yes,I think using the boost MPI library is a good idea
